# Generated by Django 4.0.10 on 2024-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('S', 'Supplier'), ('M', 'Manufacturer'), ('D', 'Distributor'), ('R', 'Retailer'), ('C', 'Customer')], default='R', max_length=1)),
                ('address', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
