# Generated by Django 4.0.10 on 2024-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
