# Generated by Django 4.0.10 on 2024-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0003_auto_20240312_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=150)),
                ('m_id', models.CharField(max_length=150)),
                ('s_msg', models.CharField(max_length=150)),
                ('m_msg', models.CharField(max_length=150)),
            ],
        ),
    ]
