# Generated by Django 4.2.4 on 2024-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=22)),
            ],
        ),
    ]
