# Generated by Django 4.2.4 on 2024-04-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0006_chat_delete_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
